version: '3'

services:
  database:
    container_name: DB-Container
    restart: always
    build:
      context: ./docker/database 
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data.sql:docker-entrypoint-initdb.d/data.sql
  php-fpm:
    container_name: PHP-FPM-Container
    build:
      context: ./docker/php-fpm 
    volumes:
      - ./src:/var/www
  nginx:
    container_name: NGINX-Container
    build:
      context: ./docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm 
    ports:
      - "8081:8081"
      - "433:433"